project:
  type: website

website:
  page-navigation: true
  title: "R for Statistical Data Science"
  site-url: "https://r-programming-course.netlify.app"

  repo-url: https://github.com/StevenGolovkine/MSDSSLTFA_R_course
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Steven Golovkine"
    background: "#fdf5e6"

  sidebar:
    background: "#fdf5e6"
    logo: "./include/logo.svg"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/StevenGolovkine/MSDSSLTFA_R_course
        text: "GitHub organization"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: information/overview.qmd
            text: Overview
          - href: information/syllabus.qmd
            text: Syllabus
          - href: information/assessment.qmd
            text: Assessment
          - href: information/support.qmd
            text: Support
          - href: index.qmd
            text: Schedule
          - href: information/links.qmd
            text: Useful links
          - href: information/faq.qmd
            text: FAQ
          - href: information/update.qmd
            text: Updates
      - section: "Weekly materials"
        contents:
          - href: weeks/week-1.qmd
            text: "Week 1"
          - href: weeks/week-2.qmd
            text: "Week 2"
          - href: weeks/week-3.qmd
            text: "Week 3"
          - href: weeks/week-4.qmd
            text: "Week 4"
          - href: weeks/week-5.qmd
            text: "Week 5"
          - href: weeks/week-6.qmd
            text: "Week 6"
          - href: weeks/week-7.qmd
            text: "Week 7"
          - href: weeks/week-8.qmd
            text: "Week 8"
          - href: weeks/week-9.qmd
            text: "Week 9"
          - href: weeks/week-10.qmd
            text: "Week 10"
          - href: weeks/week-11.qmd
            text: "Week 11"
          - href: weeks/week-12.qmd
            text: "Week 12"

bibliography: bibliography.bib

format:
  html:
    theme:
      light: [cosmo]
    css:
    - ./ul.css
    - include/webex.css
    code-copy: true
    code-overflow: wrap
    toc: true
    smooth-scroll: true
    include-after-body: include/webex.js

freeze: auto

editor: visual