project:
  type: website

website:
  page-navigation: false
  title: "R for Statistical Data Science"
  site-url: "https://r-programming-course.netlify.app"
  repo-url: https://github.com/StevenGolovkine/MSDSSLTFA_R_course
  repo-actions: [issue, edit]
  open-graph: true

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Steven Golovkine"
    background: "#fdf5e6"

  sidebar:
    background: "#fdf5e6"
    logo: "./include/logo.svg"
    pinned: true
    align: center
    toc-location: right
    tools:
      - icon: github
        href: https://github.com/StevenGolovkine/MSDSSLTFA_R_course
        text: "GitHub organization"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: information/overview.qmd
            text: Overview
          - href: information/syllabus.qmd
            text: Information
          - href: information/assessment.qmd
            text: Assessment
          - href: information/support.qmd
            text: Support
          - href: index.qmd
            text: Topics
          - href: information/links.qmd
            text: Useful links
          - href: information/faq.qmd
            text: FAQ
          - href: information/update.qmd
            text: Updates
      - section: "Topics"
        contents:
          - href: weeks/week-1.qmd
            text: "1 - R Basics"
          - href: weeks/week-2.qmd
            text: "2 - Tidyverse"
          - href: weeks/week-3.qmd
            text: "3 - Extract, transform and load"
          - href: weeks/week-4.qmd
            text: "4 - Data visualisation"
          - href: weeks/week-5.qmd
            text: "5 - Reproducibility"
          - href: weeks/week-6.qmd
            text: "6 - Interactivity"
          - href: weeks/week-7.qmd
            text: "7 - Memory issues"
          - href: weeks/week-8.qmd
            text: "8 - Simulation"
          - href: weeks/week-9.qmd
            text: "9 - Code debugging"
          - href: weeks/week-10.qmd
            text: "10 - C++"

bibliography: bibliography.bib

format:
  html:
    theme:
      light: [cosmo]
    css:
    - ./ul.css
    - include/webex.css
    code-copy: true
    code-overflow: wrap
    toc: true
    smooth-scroll: true
    include-after-body: include/webex.js


freeze: auto

editor: visual