project:
  type: book

book:
  title: "R programming course"
  author: "Steven Golovkine"
  date: "7/30/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css:
    - ./ul.css
    - include/webex.css
    smooth-scroll: true
    include-after-body: include/webex.js
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

